/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ExPopulusToken,
  ExPopulusTokenInterface,
} from "../ExPopulusToken";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "mintToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50606d80601d6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80632004ffd914602d575b600080fd5b60336035565b005b56fea26469706673582212206e550475b25e2744a428d540e24941fdebf30e98d8198d6ca584d825f2334df164736f6c634300080c0033";

export class ExPopulusToken__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ExPopulusToken> {
    return super.deploy(overrides || {}) as Promise<ExPopulusToken>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ExPopulusToken {
    return super.attach(address) as ExPopulusToken;
  }
  connect(signer: Signer): ExPopulusToken__factory {
    return super.connect(signer) as ExPopulusToken__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExPopulusTokenInterface {
    return new utils.Interface(_abi) as ExPopulusTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExPopulusToken {
    return new Contract(address, _abi, signerOrProvider) as ExPopulusToken;
  }
}
