import { BigNumber } from "ethers";

export const BATTLE_1_DATA = [
  [
    0,
    0,
    BigNumber.from("1"),
    BigNumber.from("0"),
    { eventType: 0 },
    { playerType: 0 },
    { abilityId: BigNumber.from("1") },
    { attackDamage: BigNumber.from("0") },
  ],
  [
    0,
    1,
    BigNumber.from("1"),
    BigNumber.from("0"),
    { eventType: 0 },
    { playerType: 1 },
    { abilityId: BigNumber.from("1") },
    { attackDamage: BigNumber.from("0") },
  ],
  [
    1,
    0,
    BigNumber.from("0"),
    BigNumber.from("50"),
    { eventType: 1 },
    { playerType: 0 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("50") },
  ],
  [
    1,
    1,
    BigNumber.from("0"),
    BigNumber.from("50"),
    { eventType: 1 },
    { playerType: 1 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("50") },
  ],
  [
    1,
    0,
    BigNumber.from("0"),
    BigNumber.from("50"),
    { eventType: 1 },
    { playerType: 0 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("50") },
  ],
  [
    1,
    1,
    BigNumber.from("0"),
    BigNumber.from("50"),
    { eventType: 1 },
    { playerType: 1 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("50") },
  ],
  [
    2,
    1,
    BigNumber.from("0"),
    BigNumber.from("0"),
    { eventType: 2 },
    { playerType: 1 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("0") },
  ],
  [
    0,
    1,
    BigNumber.from("1"),
    BigNumber.from("0"),
    { eventType: 0 },
    { playerType: 1 },
    { abilityId: BigNumber.from("1") },
    { attackDamage: BigNumber.from("0") },
  ],
  [
    1,
    0,
    BigNumber.from("0"),
    BigNumber.from("50"),
    { eventType: 1 },
    { playerType: 0 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("50") },
  ],
  [
    1,
    1,
    BigNumber.from("0"),
    BigNumber.from("50"),
    { eventType: 1 },
    { playerType: 1 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("50") },
  ],
  [
    2,
    0,
    BigNumber.from("0"),
    BigNumber.from("0"),
    { eventType: 2 },
    { playerType: 0 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("0") },
  ],
  [
    0,
    0,
    BigNumber.from("2"),
    BigNumber.from("0"),
    { eventType: 0 },
    { playerType: 0 },
    { abilityId: BigNumber.from("2") },
    { attackDamage: BigNumber.from("0") },
  ],
  [
    1,
    0,
    BigNumber.from("0"),
    BigNumber.from("55"),
    { eventType: 1 },
    { playerType: 0 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("55") },
  ],
  [
    1,
    1,
    BigNumber.from("0"),
    BigNumber.from("55"),
    { eventType: 1 },
    { playerType: 1 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("55") },
  ],
  [
    1,
    0,
    BigNumber.from("0"),
    BigNumber.from("55"),
    { eventType: 1 },
    { playerType: 0 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("55") },
  ],
  [
    1,
    1,
    BigNumber.from("0"),
    BigNumber.from("55"),
    { eventType: 1 },
    { playerType: 1 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("55") },
  ],
  [
    2,
    0,
    BigNumber.from("0"),
    BigNumber.from("0"),
    { eventType: 2 },
    { playerType: 0 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("0") },
  ],
  [
    2,
    1,
    BigNumber.from("0"),
    BigNumber.from("0"),
    { eventType: 2 },
    { playerType: 1 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("0") },
  ],
  [
    0,
    0,
    BigNumber.from("1"),
    BigNumber.from("0"),
    { eventType: 0 },
    { playerType: 0 },
    { abilityId: BigNumber.from("1") },
    { attackDamage: BigNumber.from("0") },
  ],
  [
    0,
    1,
    BigNumber.from("1"),
    BigNumber.from("0"),
    { eventType: 0 },
    { playerType: 1 },
    { abilityId: BigNumber.from("1") },
    { attackDamage: BigNumber.from("0") },
  ],
  [
    1,
    0,
    BigNumber.from("0"),
    BigNumber.from("55"),
    { eventType: 1 },
    { playerType: 0 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("55") },
  ],
  [
    1,
    1,
    BigNumber.from("0"),
    BigNumber.from("55"),
    { eventType: 1 },
    { playerType: 1 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("55") },
  ],
  [
    1,
    0,
    BigNumber.from("0"),
    BigNumber.from("55"),
    { eventType: 1 },
    { playerType: 0 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("55") },
  ],
  [
    1,
    1,
    BigNumber.from("0"),
    BigNumber.from("55"),
    { eventType: 1 },
    { playerType: 1 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("55") },
  ],
  [
    2,
    1,
    BigNumber.from("0"),
    BigNumber.from("0"),
    { eventType: 2 },
    { playerType: 1 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("0") },
  ],
  [
    3,
    1,
    BigNumber.from("0"),
    BigNumber.from("0"),
    { eventType: 3 },
    { playerType: 1 },
    { abilityId: BigNumber.from("0") },
    { attackDamage: BigNumber.from("0") },
  ],
];
